import { readFile, writeFile } from 'node:fs/promises';
import { train } from '../src/learning.js';
const data = JSON.parse(await readFile(new URL('../data/intents.pt.json', import.meta.url), 'utf8'));
const model = train(data);
await writeFile(new URL('../src/intent-model.js', import.meta.url), `// Generated by npm run train:ai. Training data: data/intents.pt.json.\nexport default ${JSON.stringify(model, null, 2)};\n`);
console.log(`Modelo local treinado: ${model.examples} exemplos; ${model.vocabulary.length} palavras; ${Object.keys(model.classes).length} intenções.`);
